export default [
  {
    id: 1,
    coverImg: 'old_port.png',
    title: 'My Portfolio',
    description: 'My other portfolio',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript',
    liveUrl: 'https://aninditapriyadarshini.github.io/My-Portfolio/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/My-Portfolio',
  },

  {
    id: 2,
    coverImg: 'floret_min.png',
    title: 'Floret',
    description: 'A Flower Shop Website',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript',
    liveUrl: 'https://floret.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Floret',
  },

  {
    id: 3,
    coverImg: 'study_buddy.png',
    title: 'Study-Buddy',
    description:
      'A Multiple page resposive website, with tools to help in your studies.',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript & API',
    liveUrl: 'https://study-buddy-study.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Study-Buddy',
  },

  {
    id: 4,
    coverImg: 'carbon_foots.png',
    title: 'Carbon Foots',
    description: 'A website to calculate ones Carbon Footprints.',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript',
    liveUrl: 'https://carbonfoots.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Carbon-Foots',
  },

  {
    id: 5,
    coverImg: 'form-1.png',
    title: 'SignUp Form',
    description: 'A Signup/Login Form.',
    techStack1: 'React',
    techStack2: 'State',
    techStack3: 'React-Forms',
    liveUrl: 'https://signup-formm.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/SignUp-form',
  },

  {
    id: 6,
    coverImg: 'width-tracker.png',
    title: 'Window Width Tracker',
    description:
      'Its a Windows Width Tracker, it basically shows the width of the current window screen, as the size of the screen is increased or decreased .',
    techStack1: 'React',
    techStack2: 'Hooks',
    techStack3: 'States',
    liveUrl: 'https://windows-width-tracker.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Windows-Width-Tracker',
  },

  {
    id: 7,
    coverImg: 'travel.png',
    title: 'Travel Journal',
    description: 'Its a Travel Journal Blog-style page.',
    techStack1: 'React',
    techStack2: 'Components',
    techStack3: 'Props',
    liveUrl: 'https://travel-jour.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Travel-Journal',
  },

  {
    id: 8,
    coverImg: 'r-p-s.png',
    title: 'Rock, Paper, Scissor',
    description: 'My version of the famous game, rock,paper, scissor.',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript',
    liveUrl: 'https://rock-paper-scissor-ga.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/My-Portfolio',
  },

  {
    id: 9,
    coverImg: 'form-2.png',
    title: 'Registration Form',
    description: 'My other portfolio',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'Forms',
    liveUrl: 'https://registration-forrm.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/Registration-Form',
  },

  {
    id: 10,
    coverImg: 'calc.png',
    title: 'Calculator',
    description: 'My version of Calculator.',
    techStack1: 'HTML',
    techStack2: 'CSS',
    techStack3: 'JavaScript',
    liveUrl: 'https://calc-math.netlify.app/',
    gitUrl: 'https://github.com/ANINDITAPRIYADARSHINI/My-Portfolio',
  },
];
